#include "commands/client_login.c"
#include "commands/client_logout.c"
#include "commands/client_unregister.c"
#include "commands/translate_buff.c"
#include "commands/open_a.c"
#include "commands/read_input.c"    